apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: asm-gcp
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: istio-internal-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            cloud.google.com/load-balancer-type: "internal"
          service:
            ports:
              - name: status-port
                port: 15020
              - name: http2
                port: 80
              - name: https
                port: 443
          overlays:
            - kind: HorizontalPodAutoscaler
              name: istio-internal-ingressgateway
              patches:
                - path: metadata.labels.app
                  value: istio-internal-ingressgateway
                - path: metadata.labels.istio
                  value: internal-ingressgateway
                - path: spec.scaleTargetRef.name
                  value: istio-internal-ingressgateway
            - kind: Deployment
              name: istio-internal-ingressgateway
              patches:
                - path: metadata.labels.app
                  value: istio-internal-ingressgateway
                - path: metadata.labels.istio
                  value: internal-ingressgateway
                - path: spec.selector.matchLabels.app
                  value: istio-internal-ingressgateway
                - path: spec.selector.matchLabels.istio
                  value: internal-ingressgateway
                - path: spec.template.metadata.labels.app
                  value: istio-internal-ingressgateway
                - path: spec.template.metadata.labels.istio
                  value: internal-ingressgateway
            - kind: Service
              name: istio-internal-ingressgateway
              patches:
                - path: metadata.labels.app
                  value: istio-internal-ingressgateway
                - path: metadata.labels.istio
                  value: internal-ingressgateway
                - path: spec.selector.app
                  value: istio-internal-ingressgateway
                - path: spec.selector.istio
                  value: internal-ingressgateway
  meshConfig:
    accessLogFile: "/dev/stdout"